version: "2"
services:
  eswatini-cmis-ui:
    image: openlmis/dev-ui:9.0.2
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
    depends_on:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
  auth-ui:
    image: openlmis/auth-ui:6.2.6
    volumes:
      - '/openlmis-auth-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.6.5
    volumes:
      - '/openlmis-referencedata-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:2.0.9
    volumes:
     - '/openlmis-stockmanagement-ui'
  ui-components:
    image: openlmis/ui-components:7.2.5
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.0.9
    volumes:
      - '/openlmis-ui-layout'
  image:
    build: .
    image: kausamusa/eswatini-cmis-ui
